// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfF01WACo_ve1fv1bnbElzUXHGWP2nBtE',
    appId: '1:856834623310:web:2f6fba3a1eded6766a401f',
    messagingSenderId: '856834623310',
    projectId: 'pruebas1-f9658',
    authDomain: 'pruebas1-f9658.firebaseapp.com',
    databaseURL: 'https://pruebas1-f9658-default-rtdb.firebaseio.com',
    storageBucket: 'pruebas1-f9658.firebasestorage.app',
    measurementId: 'G-WGBBJRT5G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYb61vJ60stNklu0hTvbJqiRxq1JwCVh0',
    appId: '1:856834623310:android:99c81c5fa3aa482d6a401f',
    messagingSenderId: '856834623310',
    projectId: 'pruebas1-f9658',
    databaseURL: 'https://pruebas1-f9658-default-rtdb.firebaseio.com',
    storageBucket: 'pruebas1-f9658.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSEROCCs_N46u-3riUjcGJY7NM4PNheqg',
    appId: '1:856834623310:ios:5277bc642cf1a0436a401f',
    messagingSenderId: '856834623310',
    projectId: 'pruebas1-f9658',
    databaseURL: 'https://pruebas1-f9658-default-rtdb.firebaseio.com',
    storageBucket: 'pruebas1-f9658.firebasestorage.app',
    iosBundleId: 'com.example.centroVip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSEROCCs_N46u-3riUjcGJY7NM4PNheqg',
    appId: '1:856834623310:ios:5277bc642cf1a0436a401f',
    messagingSenderId: '856834623310',
    projectId: 'pruebas1-f9658',
    databaseURL: 'https://pruebas1-f9658-default-rtdb.firebaseio.com',
    storageBucket: 'pruebas1-f9658.firebasestorage.app',
    iosBundleId: 'com.example.centroVip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfF01WACo_ve1fv1bnbElzUXHGWP2nBtE',
    appId: '1:856834623310:web:9fa28a76b425d5d76a401f',
    messagingSenderId: '856834623310',
    projectId: 'pruebas1-f9658',
    authDomain: 'pruebas1-f9658.firebaseapp.com',
    databaseURL: 'https://pruebas1-f9658-default-rtdb.firebaseio.com',
    storageBucket: 'pruebas1-f9658.firebasestorage.app',
    measurementId: 'G-XDCLM6ZX6H',
  );
}
